### ISSUE TITLE
Nothing happens when running the executable

### ISSUE THREAD

**Issue by herzog0** [akiver/boiler-writter#5]
Hi! 
When I run the executable as follows, nothing really happens after the steam startup. 
```
~/Downloads/bin >>> ./boiler-writter ./testfile 536994766969370057 722299117795130797 45650                                                                                                                                              [130]
[S_API] SteamAPI_Init(): Loaded '/home/myusr/.steam/debian-installation/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 730
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198899477983 [API loaded no]
STEAMID:76561198899477983
~/Downloads/bin >>>  
```

Could it be because the Match Share Code used is too old? 
Also, am I doing something wrong? Should Steam or CS:GO itself be running?

**Comment by akiver** [comment]
Hi,
Not sure why but this share code seems "buggy", if you try to download it from the game, the loading never ends:  
```
steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-eLvVf-RUBth-fXYLF-jpBCU-3wjjA
```
![code](https://user-images.githubusercontent.com/1842524/166099922-d1ccd2f4-9016-4ba2-a4f7-1dd769e9f3ec.png)

When a share code has expired the game displays an explicit message.
Unfortunately, since the game itself can't retrieve the match information, I don't think we can do something about it.

The exit code when downloading it from boiler-writter is `8` which means no match has been found which I think is correct for this case.

**Comment by herzog0** [comment]
Wow, what a fast response. Thank you! I will try to find a more recent share code and re-test all the steps here.
